export const STR = {
  title: {
    name: '석사과정',
    sub: '손상된 기록',
    gate: '클릭하여 기록 재생',
    restoring: (p: number) => `손상된 기록 복원 중… ${p}%`,
    headphones: '헤드폰 착용을 권장합니다',
    controls: 'WASD 이동 · 마우스 시점 · E 상호작용 · Tab 출입증 · Esc 일시정지',
    resume: '기록을 이어서 복원하시겠습니까?',
  },
  badge: {
    affil: '○○대학교 ○○연구실',
    roleBase: '학부연구생',
    roleTarget: '석사과정',
    name: '한○○',
  },
  lost: (phase: string) => `해당 구간의 기록은 유실되었습니다 — ${phase}`,
  colleague: {
    approach: ['교수님이 너 얘기 하더라.', '요즘 어때? 랩 생활.'],
    likeYou: '교수님이 너 마음에 들어하시더라.',
    choiceGood: '재밌어요. 배울 게 많아서.',
    choiceMeh: '…그냥 그렇죠, 뭐.',
  },
  doc: {
    taskTitle: '졸업생 진로 현황 업데이트',
    allGrad: '진로: 대학원 진학',
    selfRow: '한○○ — 대학원 진학 예정',
    choices: {
      accurate: '정확히 입력한다',
      mistake: '사소한 실수를 낸다',
      deleteRow: '내 이름이 있는 행을 조용히 지운다',
    },
    caught: '…방금 뭐 지웠어?',
  },
  sample: {
    title: '냉동고 샘플 분류',
    instruction: '튜브를 선택한 뒤 지시대로 분류하십시오.',
    keep: '보관',
    discard: '폐기',
    inspect: '자세히 본다',
    toothDetail: '점이 아니다. 작은 치아다.',
    wasteSubtitle: '폐기물통 안쪽에서 — 톡, 톡, 톡.',
    listen: '뚜껑에 귀를 댄다',
    seal: '그냥 봉인한다',
    voice: '…선배님.',
    sealed: '테이프로 한 번 더 감았다.',
    search: '기록을 몰래 검색한다',
    quit: '그만둔다',
    record: '폐기 대상: 실패 개체 04 — 주의: 이름을 부르지 말 것.',
    caught: '…뭐 찾아?',
  },
  ending: {
    q1: '"요즘 연구는 어때?"',
    q2: '"그런데 왜 우리 연구실에 들어왔어?"',
    corrupt: '▓▓▓▓▓▓치지직▓▓▓▓▓▓',
    accept: '"……그래."',
    exitRequest: '퇴실 요청이 접수되었습니다.',
    exit: '진학 처리되었습니다.',
    lostFinal: '이후의 기록은 복원할 수 없습니다.',
    card: '기록의 끝',
    postcredit: '한○○ · 진로 확인 필요',
    creditsNote: '이 데모는 복원된 기록의 일부입니다.',
    creditsAssets:
      '3D (CC-BY): Crawling Mutated Human © Elisey · Gaunt Horror Creature © PurplePoint · 인물 © manoeldarochadeoliveira, yuriannoue, Ace-of_spades · 소품 © Poly by Google · CC0: Quaternius, MilkAndBanana',
  },
  chase: {
    brief: '복도가 어둡다.',
    order: '교수: "면담실로 오게. 오는 길에 자료도 챙겨오고."',
    hud: (n: number, total: number) => `자료 ${n} / ${total}`,
    tip: '걸으면 조용하다 · Shift 달리기는 소리가 난다 · 문틈에 숨어라',
    pickup: ['연구 기록 A-3 회수', '실험 일지 B-7 회수', '인건비 정산서 C-1 회수'],
    locked: '자료가 모자란다. 아직 나갈 수 없다.',
    complete: '자료를 다 챙겼다. 면담실로.',
    // 자료에 적힌 것 — 주울 때마다 한 줄씩 (선배 서사)
    note: [
      '…실험 참가자 명단에 내 이름이 있다.',
      '11월 7일. 잠을 자도 아침이 오지 않는다.',
      '존재하지 않는 학생의 인건비가 정산되어 있다.',
    ],
  },
  pause: { title: '일시정지', resume: '계속하기 (클릭)' },
} as const
